/**
 * CAVER runner — wraps the Java `caver.jar` CLI
 * ----------------------------------------------
 * CAVER 3.0.3 (https://www.caver.cz) finds access tunnels from a starting
 * point to the protein surface using a Voronoi-diagram approach.  This
 * module:
 *
 * 1. Writes a config.txt from the user-supplied CaverParams
 * 2. Invokes `java -jar caver.jar -home … -pdb … -conf … -out …`
 * 3. Parses the Java-serialized tunnels .obj into plain JSON
 * 4. Returns the CaverResult for the web UI
 *
 * The algorithm is 100 % the original CAVER — no reimplementation.
 * Only the JRE (java) is required; the .obj binary is parsed by our
 * TypeScript Java-serialization reader (parse-tunnels.ts) so no JDK
 * (javac) is needed.
 */

import { readFile, writeFile, mkdir, readdir, rm } from 'fs/promises'
import { existsSync } from 'fs'
import { join } from 'path'
import { spawn } from 'child_process'
import { randomUUID } from 'crypto'
import { parseTunnelsObj, buildClusterSummaries } from './parse-tunnels'
import type { CaverParams, CaverResult, CaverTunnel } from './types'

/** Absolute path to the vendored CAVER directory. */
const CAVER_HOME = join(process.cwd(), 'vendor', 'caver')
const CAVER_JAR = join(CAVER_HOME, 'caver.jar')
const CONFIG_TEMPLATE = join(CAVER_HOME, 'config_default.txt')
const JOBS_DIR = join(process.cwd(), 'upload', 'caver-jobs')

/** Generate a CAVER config.txt from the user parameters.
 *  The template (vendor/caver/config_default.txt) provides sensible defaults;
 *  we override only the fields the user can control. */
function buildConfig(params: CaverParams): string {
  const lines: string[] = []
  lines.push('# CAVER config — generated by the web app')
  lines.push('load_tunnels no')
  lines.push('load_cluster_tree no')
  lines.push('stop_after never')
  lines.push('')
  lines.push('# Input data')
  lines.push('time_sparsity 1')
  lines.push('first_frame 1')
  lines.push('last_frame 100000')
  lines.push('')
  lines.push('# Starting point')
  lines.push(`starting_point_coordinates ${params.start_x} ${params.start_y} ${params.start_z}`)
  lines.push('')
  lines.push('# Tunnel calculation')
  lines.push(`probe_radius ${params.probe_radius}`)
  lines.push(`shell_radius ${params.shell_radius}`)
  lines.push(`shell_depth ${params.shell_depth}`)
  lines.push('')
  lines.push('# Tunnel clustering')
  lines.push('clustering average_link')
  lines.push('weighting_coefficient 1')
  lines.push(`clustering_threshold ${params.clustering_threshold}`)
  lines.push('exclude_start_zone 2')
  lines.push('exclude_end_zone 0')
  lines.push('min_middle_zone 5')
  lines.push('save_zones no')
  lines.push('')
  lines.push('# Output generation')
  lines.push('one_tunnel_in_snapshot cheapest')
  lines.push('max_output_clusters 999')
  lines.push('save_dynamics_visualization no')
  lines.push('generate_summary yes')
  lines.push('generate_tunnel_characteristics yes')
  lines.push('generate_tunnel_profiles yes')
  lines.push('generate_histograms no')
  lines.push('generate_bottleneck_heat_map no')
  lines.push('generate_profile_heat_map no')
  lines.push('compute_tunnel_residues yes')
  lines.push('residue_contact_distance 3.0')
  lines.push('compute_bottleneck_residues yes')
  lines.push('bottleneck_contact_distance 3.0')
  lines.push('')
  lines.push('# Starting point optimisation')
  lines.push(`max_distance ${params.max_distance}`)
  lines.push(`desired_radius ${params.desired_radius}`)
  lines.push('')
  lines.push('# Advanced tunnel calculation')
  lines.push(`number_of_approximating_balls ${params.number_of_approximating_balls}`)
  lines.push('add_central_sphere yes')
  lines.push(`max_number_of_tunnels ${params.max_number_of_tunnels}`)
  lines.push('max_limiting_radius 100')
  lines.push('cost_function_exponent 2')
  lines.push('automatic_shell_radius no')
  lines.push('starting_point_protection_radius 4')
  lines.push('')
  lines.push('# Frame clustering (single-frame: threshold 1 = each tunnel its own)')
  lines.push('frame_clustering yes')
  lines.push('frame_weighting_coefficient 1')
  lines.push('frame_clustering_threshold 1')
  lines.push('frame_exclude_start_zone 0')
  lines.push('frame_exclude_end_zone 0')
  lines.push('frame_min_middle_zone 5')
  lines.push('')
  lines.push('# Tunnel end averaging')
  lines.push('average_surface_frame yes')
  lines.push('average_surface_global yes')
  lines.push('average_surface_smoothness_angle 10')
  lines.push('average_surface_point_min_angle 5')
  lines.push('average_surface_tunnel_sampling_step 0.5')
  lines.push('')
  lines.push('# Approximate clustering')
  lines.push('do_approximate_clustering no')
  lines.push('')
  lines.push('# Outputs')
  lines.push('profile_tunnel_sampling_step 0.5')
  lines.push('visualization_tunnel_sampling_step 1')
  lines.push('visualize_tunnels_per_cluster 5000')
  lines.push('visualization_subsampling random')
  lines.push('compute_errors no')
  lines.push('save_error_profiles no')
  lines.push('')
  lines.push('# Others')
  lines.push('swap yes')
  if (params.seed.trim()) lines.push(`seed ${params.seed}`)
  return lines.join('\n') + '\n'
}

/** Run caver.jar on the given PDB text + parameters.
 *  Returns a CaverResult with the parsed tunnels + cluster summaries. */
export async function runCaver(
  pdbText: string,
  pdbName: string,
  params: CaverParams,
): Promise<CaverResult> {
  const jobId = randomUUID().slice(0, 8)
  const workDir = join(JOBS_DIR, jobId)
  const inputsDir = join(workDir, 'inputs')
  const outDir = join(workDir, 'out')

  await mkdir(inputsDir, { recursive: true })
  await mkdir(outDir, { recursive: true })

  // Write the PDB input (filter out ignored residues if any)
  const filteredPdb = filterResidues(pdbText, params.ignore_residues)
  const inputPdbPath = join(inputsDir, pdbName.endsWith('.pdb') ? pdbName : pdbName + '.pdb')
  await writeFile(inputPdbPath, filteredPdb, 'utf8')

  // Write the config
  const configPath = join(inputsDir, 'config.txt')
  await writeFile(configPath, buildConfig(params), 'utf8')

  // Invoke java -jar caver.jar
  const javaHeap = parseInt(params.java_heap, 10) || 1500
  const args = [
    `-Xmx${javaHeap}m`,
    '-cp', join(CAVER_HOME, 'lib'),
    '-jar', CAVER_JAR,
    '-home', CAVER_HOME,
    '-pdb', inputsDir,
    '-conf', configPath,
    '-out', outDir,
  ]

  const { stdout, stderr, code } = await runProcess('java', args, {
    timeout: 120_000, // 2 min timeout
    env: { ...process.env, LD_LIBRARY_PATH: '' },
  })

  const logText = stdout + '\n' + stderr

  // Read the log file (more detailed than stdout)
  const logPath = join(outDir, 'log.txt')
  let logTail = logText
  try {
    const logFile = await readFile(logPath, 'utf8')
    logTail = logFile.slice(-3000)
  } catch { /* use stdout */ }

  // Find the tunnels .obj file
  const tunnelsDir = join(outDir, 'data', 'tunnels')
  let tunnels: CaverTunnel[] = []
  let warnings: string[] = []

  if (existsSync(tunnelsDir)) {
    const files = await readdir(tunnelsDir)
    const objFile = files.find(f => f.endsWith('.obj'))
    if (objFile) {
      try {
        const objBuf = await readFile(join(tunnelsDir, objFile))
        tunnels = parseTunnelsObj(objBuf)
      } catch (e) {
        warnings.push(`Failed to parse tunnels: ${(e as Error).message}`)
      }
    }
  }

  if (tunnels.length === 0) {
    warnings.push('No tunnels found — try adjusting the starting point or probe radius.')
  }

  // Build cluster summaries
  const clusters = buildClusterSummaries(tunnels)

  // Reassign cluster ids based on priority (highest priority = cluster 1)
  const clusterIdMap = new Map<number, number>()
  clusters.forEach((c, i) => clusterIdMap.set(c.id, i + 1))
  tunnels = tunnels.map(t => ({ ...t, cluster_id: clusterIdMap.get(t.cluster_id) ?? t.cluster_id }))
  clusters.forEach((c, i) => { c.id = i + 1 })

  // Collect output files for download
  const files = await listFiles(outDir)

  // Summary stats
  const bns = tunnels.map(t => t.bottleneck_radius)
  const startX = parseFloat(params.start_x) || 0
  const startY = parseFloat(params.start_y) || 0
  const startZ = parseFloat(params.start_z) || 0

  return {
    job_id: jobId,
    starting_point: [startX, startY, startZ],
    tunnels,
    clusters,
    summary: {
      n_tunnels: tunnels.length,
      n_clusters: clusters.length,
      max_bottleneck: bns.length ? Math.max(...bns) : null,
      min_bottleneck: bns.length ? Math.min(...bns) : null,
      probe_radius: parseFloat(params.probe_radius) || 0,
      shell_radius: parseFloat(params.shell_radius) || 0,
      shell_depth: parseFloat(params.shell_depth) || 0,
    },
    files,
    log_tail: logTail,
    returncode: code,
    error: code !== 0 && tunnels.length === 0
      ? `CAVER exited with code ${code}. Check the log for details.`
      : null,
    warnings,
  }
}

/** Get the path to a CAVER job's output directory. */
export function getCaverJobDir(jobId: string): string {
  return join(JOBS_DIR, jobId)
}

/** Remove residues from a PDB text by residue name (e.g. "HOH WAT").
 *  Only filters ATOM/HETATM records. */
function filterResidues(pdbText: string, ignoreList: string): string {
  const ignore = ignoreList.trim().split(/\s+/).filter(Boolean)
  if (ignore.length === 0) return pdbText
  const ignoreSet = new Set(ignore.map(r => r.toUpperCase()))
  return pdbText
    .split('\n')
    .filter(line => {
      if (!line.startsWith('ATOM') && !line.startsWith('HETATM')) return true
      const resName = line.slice(17, 20).trim().toUpperCase()
      return !ignoreSet.has(resName)
    })
    .join('\n')
}

/** Recursively list all files in a directory (relative paths). */
async function listFiles(dir: string, prefix = ''): Promise<string[]> {
  const out: string[] = []
  if (!existsSync(dir)) return out
  const entries = await readdir(dir, { withFileTypes: true })
  for (const entry of entries) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name
    if (entry.isDirectory()) {
      out.push(...await listFiles(join(dir, entry.name), rel))
    } else {
      out.push(rel)
    }
  }
  return out
}

/** Spawn a child process and wait for it, collecting stdout+stderr. */
function runProcess(
  cmd: string,
  args: string[],
  opts: { timeout: number; env?: NodeJS.ProcessEnv },
): Promise<{ stdout: string; stderr: string; code: number }> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, {
      env: opts.env,
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    let stdout = ''
    let stderr = ''
    let killed = false
    const timer = setTimeout(() => {
      killed = true
      child.kill('SIGKILL')
    }, opts.timeout)
    child.stdout.on('data', d => { stdout += d.toString() })
    child.stderr.on('data', d => { stderr += d.toString() })
    child.on('error', err => {
      clearTimeout(timer)
      reject(err)
    })
    child.on('close', code => {
      clearTimeout(timer)
      if (killed) {
        resolve({ stdout, stderr: stderr + '\n[Timed out]', code: -1 })
      } else {
        resolve({ stdout, stderr, code: code ?? -1 })
      }
    })
  })
}
